from pydantic import BaseModel, Field

class LLMRequest(BaseModel):
    prompt: str = Field(..., min_length=1, description="The prompt to send to the LLM")

class LLMResponse(BaseModel):
    answer: str = Field(..., description="The response generated by the LLM")
